export const SET_ROOT_STAKE_TO_PANEL = 'SET_ROOT_STAKE_TO_PANEL'
export const SET_ROOT_ANNOUNCE_WITHDRAWAL = 'SET_ROOT_ANNOUNCE_WITHDRAWAL'
export const SET_ROOT_WITHDRAW = 'SET_ROOT_WITHDRAW'

export const GET_ROOT_MEMBERS = 'GET_ROOT_MEMBERS'
export const SET_ROOT_MEMBERS = 'SET_ROOT_MEMBERS'

export const GET_CHECK_IS_USER_ROOT_NODE = 'GET_CHECK_IS_USER_ROOT_NODE'
export const SET_CHECK_IS_USER_ROOT_NODE = 'SET_CHECK_IS_USER_ROOT_NODE'

export const GET_ROOT_NODE_STAKES = 'GET_ROOT_NODE_STAKES'
export const SET_ROOT_NODE_STAKES = 'SET_ROOT_NODE_STAKES'

export const GET_ROOT_WITHDRAWALS = 'GET_ROOT_WITHDRAWALS'
export const SET_ROOT_WITHDRAWALS = 'SET_ROOT_WITHDRAWALS'

export const GET_ROOT_MINIMUM_TIME_LOCK = 'GET_ROOT_MINIMUM_TIME_LOCK'
export const SET_ROOT_MINIMUM_TIME_LOCK = 'SET_ROOT_MINIMUM_TIME_LOCK'

export const SET_ROOT_TIME_LOCKS = 'SET_ROOT_TIME_LOCKS'
export const GET_ROOT_TIME_LOCKS = 'GET_ROOT_TIME_LOCKS'
