export const GET_QEXPERT_PROPOSALS = "GET_QEXPERT_PROPOSALS";
export const GET_QEXPERT_PROPOSALS_SUCCESS = "GET_QEXPERT_PROPOSALS_SUCCESS";
export const GET_QEXPERT_PROPOSALS_ERROR = "GET_QEXPERT_PROPOSALS_ERROR";

export const GET_QEXPERT_PROPOSAL = "GET_QEXPERT_PROPOSAL";
export const GET_QEXPERT_PROPOSAL_SUCCESS = "GET_QEXPERT_PROPOSAL_SUCCESS";
export const GET_QEXPERT_PROPOSAL_ERROR = "GET_QEXPERT_PROPOSAL_ERROR";
