export const SET_CREATED_PROPOSAL_OBJECT = "GET_CREATED_PROPOSAL_OBJECT";

export const SET_CREATED_STEPS_LIMIT = "SET_CREATED_STEPS_LIMIT";
export const SET_STEP_COUNTER = "SET_STEP_COUNTER";

export const SET_DISABLED_CREATED_PROPOSAL_BTN = "SET_DISABLED_CREATED_PROPOSAL_BTN";

export const CREATE_PROPOSAL = "CREATE_PROPOSAL";
export const CREATE_PROPOSAL_SUCCESS = "CREATE_PROPOSAL_SUCCESS";

export const SET_VOTE_PROPOSAL_OBJECT = "SET_VOTE_PROPOSAL_OBJECT";
export const SET_STEP_VOTE_COUNTER = "SET_STEP_VOTE_COUNTER";
export const VOTE_FOR_PROPOSAL = "VOTE_FOR_PROPOSAL";
export const VOTE_FOR_PROPOSAL_SUCCESS = "VOTE_FOR_PROPOSAL_SUCCESS";

export const GET_ENDED_PROPOSALS = "GET_ENDED_PROPOSALS";
export const GET_ENDED_PROPOSALS_SUCCESS = "GET_ENDED_PROPOSALS_SUCCESS";
export const GET_ENDED_PROPOSALS_ERROR = "GET_ENDED_PROPOSALS_ERROR";

export const EXECUTE_PROPOSAL = "EXECUTE_PROPOSAL";
export const EXECUTE_PROPOSAL_SUCCESS = "EXECUTE_PROPOSAL_SUCCESS";
export const EXECUTE_PROPOSAL_ERROR = "EXECUTE_PROPOSAL_ERROR";
