export const GET_Q_PROPOSALS = "GET_Q_PROPOSALS";
export const GET_Q_PROPOSALS_SUCCESS = "GET_Q_PROPOSALS_SUCCESS";
export const GET_Q_PROPOSALS_ERROR = "GET_Q_PROPOSALS_ERROR";

export const GET_Q_PROPOSAL = "GET_Q_PROPOSAL";
export const GET_Q_PROPOSAL_SUCCESS = "GET_Q_PROPOSAL_SUCCESS";
export const GET_Q_EMPTY_PROPOSAL_SUCCESS = "GET_Q_EMPTY_PROPOSAL_SUCCESS";
export const GET_Q_PROPOSAL_ERROR = "GET_Q_PROPOSAL_ERROR";
