export const GET_QEXPERT_PROPOSALS = "GET_QEXPERT_PROPOSALS";
export const GET_QEXPERT_PROPOSALS_SUCCESS = "GET_QEXPERT_PROPOSALS_SUCCESS";
export const GET_QEXPERT_PROPOSALS_ERROR = "GET_QEXPERT_PROPOSALS_ERROR";

export const SET_CREATED_PROPOSAL_OBJECT = "GET_CREATED_PROPOSAL_OBJECT";
