export const GET_ROOT_VOTING_PROPOSALS = "GET_ROOT_VOTING_PROPOSALS";
export const GET_ROOT_VOTING_PROPOSALS_SUCCESS = "GET_ROOT_VOTING_PROPOSALS_SUCCESS";
export const GET_ROOT_VOTING_PROPOSALS_ERROR = "GET_ROOT_VOTING_PROPOSALS_ERROR";

export const CREATE_ROOT_VOTING_PROPOSAL = "CREATE_ROOT_VOTING_PROPOSALS";
export const CREATE_ROOT_VOTING_PROPOSAL_SUCCESS = "CREATE_ROOT_VOTING_PROPOSALS_SUCCESS";
export const CREATE_ROOT_VOTING_PROPOSAL_ERROR = "CREATE_ROOT_VOTING_PROPOSALS_ERROR";
