export const GET_ROOT_VOTING_PROPOSALS = "GET_ROOT_VOTING_PROPOSALS";
export const GET_ROOT_VOTING_PROPOSALS_SUCCESS = "GET_ROOT_VOTING_PROPOSALS_SUCCESS";
export const GET_ROOT_VOTING_PROPOSALS_ERROR = "GET_ROOT_VOTING_PROPOSALS_ERROR";

