export const GET_SLASHING_VOTING_PROPOSALS = "GET_SLASHING_VOTING_PROPOSALS";
export const GET_SLASHING_VOTING_PROPOSALS_SUCCESS = "GET_SLASHING_VOTING_PROPOSALS_SUCCESS";
export const GET_SLASHING_VOTING_PROPOSALS_ERROR = "GET_SLASHING_VOTING_PROPOSALS_ERROR";

export const GET_SLASHING_VOTING_PROPOSAL = "GET_SLASHING_VOTING_PROPOSAL";
export const GET_SLASHING_VOTING_PROPOSAL_SUCCESS = "GET_SLASHING_VOTING_PROPOSAL_SUCCESS";
export const GET_SLASHING_VOTING_PROPOSAL_ERROR = "GET_SLASHING_VOTING_PROPOSAL_ERROR";
