
export const GET_ACCOUNT_BALANCE = 'GET_ACCOUNT_BALANCE';
export const SET_ACCOUNT_BALANCE = 'SET_ACCOUNT_BALANCE';

export const GET_QV_USER_BALANCE = 'GET_QV_USER_BALANCE';
export const SET_QV_USER_BALANCE = 'SET_QV_USER_BALANCE';

export const GET_QV_LOCKED_ASSETS = 'GET_QV_LOCKED_ASSETS';
export const SET_QV_LOCKED_ASSETS = 'SET_QV_LOCKED_ASSETS';

// Action without write to Store
export const SET_QV_DEPOSIT_CALL = 'SET_QV_DEPOSIT_CALL';
export const SET_SEND_CALL = 'SET_SEND_CALL';
export const SET_QV_WITHDRAW_CALL = 'SET_QV_WITHDRAW_CALL';
export const SET_QV_LOCK_AMOUNT = 'SET_QV_LOCK_AMOUNT';
export const SET_QV_UNLOCK_AMOUNT = 'SET_QV_UNLOCK_AMOUNT';
export const SET_DELEGATE_STAKE = 'SET_DELEGATE_STAKE';

export const GET_DELEGATIONS_LIST = 'GET_DELEGATIONS_LIST';
export const GET_DELEGATIONS_LIST_SUCCESS = 'GET_DELEGATIONS_LIST_SUCCESS';
export const GET_DELEGATIONS_LIST_ERROR = 'GET_DELEGATIONS_LIST_ERROR';
export const GET_DELEGATION_INFO = 'GET_DELEGATION_INFO';
export const SET_DELEGATION_INFO = 'SET_DELEGATION_INFO';

export const GET_QV_BALANCE = 'GET_QV_BALANCE';
export const GET_QV_BALANCE_SUCCESS = 'GET_QV_BALANCE_SUCCESS';

export const ON_CLAIM_STAKE_DELEGATOR_REWARD = 'ON_CLAIM_STAKE_DELEGATOR_REWARD';

export const SET_ANNOUNCE_VOTING_AGENT = 'SET_ANNOUNCE_VOTING_AGENT';
export const SET_NEW_VOTING_AGENT = 'SET NEW VOTING AGENT';

export const GET_DELEGATION_STAKE_INFO = 'GET_DELEGATION_STAKE_INFO';
export const GET_DELEGATION_STAKE_INFO_SUCCESS = 'GET_DELEGATION_STAKE_INFO_SUCCESS';
export const GET_DELEGATION_STAKE_INFO_ERROR = 'GET_DELEGATION_STAKE_INFO_ERROR';

export const GET_QVAULT_MINIMUM_TIME_LOCK = 'GET_QVAULT_MINIMUM_TIME_LOCK';
export const GET_QVAULT_TIME_LOCKS = 'GET_QVAULT_TIME_LOCKS';

export const SET_QVAULT_MINIMUM_TIME_LOCK = 'SET_QVAULT_MINIMUM_TIME_LOCK';
export const SET_QVAULT_TIME_LOCKS = 'SET_QVAULT_TIME_LOCKS';
