export const GET_DEFAULT_ALLOCATION_PROXY = 'GET_DEFAULT_ALLOCATION_PROXY';
export const GET_DEFAULT_ALLOCATION_PROXY_ERROR = 'GET_DEFAULT_ALLOCATION_PROXY_ERROR';
export const GET_DEFAULT_ALLOCATION_PROXY_SUCCESS = 'GET_DEFAULT_ALLOCATION_PROXY_SUCCESS';

export const GET_ROOT_NODE_REWARD_PROXY = 'GET_ROOT_NODE_REWARD_PROXY';
export const GET_ROOT_NODE_REWARD_PROXY_ERROR = 'GET_ROOT_NODE_REWARD_PROXY_ERROR';
export const GET_ROOT_NODE_REWARD_PROXY_SUCCESS = 'GET_ROOT_NODE_REWARD_PROXY_SUCCESS';

export const GET_VALIDATION_REWARD_PROXY = 'GET_VALIDATION_REWARD_PROXY';
export const GET_VALIDATION_REWARD_PROXY_ERROR = 'GET_VALIDATION_REWARD_PROXY_ERROR';
export const GET_VALIDATION_REWARD_PROXY_SUCCESS = 'GET_VALIDATION_REWARD_PROXY_SUCCESS';

export const GET_Q_HOLDER_TIME_UPDATE = 'GET_Q_HOLDER_TIME_UPDATE';
export const GET_Q_HOLDER_TIME_UPDATE_ERROR = 'GET_Q_HOLDER_TIME_UPDATE_ERROR';
export const GET_Q_HOLDER_TIME_UPDATE_SUCCESS = 'GET_Q_HOLDER_TIME_UPDATE_SUCCESS';
