image: docker:stable

variables:
  IMAGE: qdevelopment/dapp:$CI_COMMIT_TAG
  IMAGE_LATEST: qdevelopment/dapp:latest

services:
  - docker:stable-dind

stages:
  - build
  - deploy

.docker-login: &docker-login
  before_script:
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASS

.host-login: &host-login
  before_script:
    - mkdir -p ~/.ssh
    - ssh-keyscan $DEPLOY_HOST >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - cp $DEPLOY_KEY ~/.ssh/id_rsa
    - cp $DEPLOY_PUBKEY ~/.ssh/id_rsa.pub
    - chmod 600 ~/.ssh/id_rsa ~/.ssh/id_rsa.pub

.host-deploy: &host-deploy
  script:
    - ssh $DEPLOY_USER@$DEPLOY_HOST "mkdir -p ~/dapp"
    - scp production.yml $DEPLOY_USER@$DEPLOY_HOST:~/dapp/docker-compose.yml
    - ssh $DEPLOY_USER@$DEPLOY_HOST "cd ~/dapp && IMAGE=$IMAGE docker-compose pull && IMAGE=$IMAGE docker-compose up -d"

compile:
  image: node:lts
  stage: build
  only:
    - master
    - merge_request
  script:
    - npm config set '//gitlab.com/api/v4/packages/npm/:_authToken' $NPM_TOKEN
    - npm ci
    - npm run build

build:
  <<: [*docker-login]
  stage: build
  only:
    - /^v.*$/
  except:
    - branches
  script:
    - docker build --build-arg NPM_TOKEN -t $IMAGE -t $IMAGE_LATEST .
    - docker push $IMAGE
    - docker push $IMAGE_LATEST

build-testnet:
  <<: [*docker-login]
  stage: build
  rules:
    - if: '$CI_COMMIT_TAG == "testnet"'
  script:
    - docker build --build-arg NPM_TOKEN -t $IMAGE .
    - docker push $IMAGE

deploy:
  <<: [*host-login]
  <<: [*host-deploy]
  stage: deploy
  only:
    - /^v.*$/
  except:
    - branches

deploy-testnet:
  <<: [*host-login]
  <<: [*host-deploy]
  stage: deploy
  rules:
    - if: '$CI_COMMIT_TAG == "testnet"'
  environment:
    name: testnet
