image: docker:stable

variables:
  IMAGE: qdevelopment/dapp:$CI_COMMIT_TAG
  IMAGE_LATEST: qdevelopment/dapp:latest

services:
  - docker:stable-dind

stages:
  - build
  - deploy

.docker-login: &docker-login
  before_script:
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASS

.host-login: &host-login
  before_script:
    - mkdir -p ~/.ssh
    - ssh-keyscan $DEPLOY_HOST >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - cp $DEPLOY_KEY ~/.ssh/id_rsa
    - cp $DEPLOY_PUBKEY ~/.ssh/id_rsa.pub
    - chmod 600 ~/.ssh/id_rsa ~/.ssh/id_rsa.pub

build:
  <<: [*docker-login]
  stage: build
  only: [tags]
  script:
    - cd client/
    - docker build -t $IMAGE -t $IMAGE_LATEST .
    - docker push $IMAGE
    - docker push $IMAGE_LATEST

deploy:
  <<: [*host-login]
  stage: deploy
  only:
    - /^v.*$/
  except:
    - branches
  variables:
    DEPLOY_DIR: ~/dapp
  script:
    - ssh $DEPLOY_USER@$DEPLOY_HOST "mkdir -p $DEPLOY_DIR"
    - scp client/production.yml $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_DIR/docker-compose.yml
    - ssh $DEPLOY_USER@$DEPLOY_HOST "cd $DEPLOY_DIR && IMAGE=$IMAGE docker-compose up -d"

deploy-testnet:
  <<: [*host-login]
  stage: deploy
  rules:
    - if: '$CI_COMMIT_TAG == "testnet"'
  environment:
    name: testnet
  variables:
    DEPLOY_DIR: ~/dapp
  script:
    - ssh $DEPLOY_USER@$DEPLOY_HOST "mkdir -p $DEPLOY_DIR"
    - scp client/production.yml $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_DIR/docker-compose.yml
    - ssh $DEPLOY_USER@$DEPLOY_HOST "cd $DEPLOY_DIR && IMAGE=$IMAGE docker-compose up -d"
