export const SET_CREATED_OBJECT = 'SET_CREATED_OBJECT';

export const SET_CREATED_STEPS_LIMIT = 'SET_CREATED_STEPS_LIMIT';
export const SET_STEP_COUNTER = 'SET_STEP_COUNTER';

export const SET_DISABLED_CREATED_OBJ_BTN = 'SET_DISABLED_CREATED_OBJ_BTN';
