export const GET_BALANCES = 'GET_BALANCES';

export const SET_TRANSACTION_LOADING = 'SET_TRANSACTION_LOADING';
export const SET_TRANSACTION_LOADING_SUCCESS = 'SET_TRANSACTION_LOADING_SUCCESS';
export const SET_TRANSACTION_LOADING_ERROR = 'SET_TRANSACTION_LOADING_ERROR';

export const SET_CLEAR_MESSAGES = 'SET_CLEAR_MESSAGES';
