export const SET_TRANSACTION_LOADING = 'SET_TRANSACTION_LOADING';
export const SET_TRANSACTION_LOADING_SUCCESS = 'SET_TRANSACTION_LOADING_SUCCESS';
export const SET_TRANSACTION_LOADING_ERROR = 'SET_TRANSACTION_LOADING_ERROR';
export const SET_TRANSACTION_COUNTER = 'SET_TRANSACTION_COUNTER';
export const SET_ERROR_MESSAGE = 'SET_ERROR_MESSAGE';
