export const GET_VALIDATOR_TOTAL_STAKE = 'GET_VALIDATOR_TOTAL_STAKE';
export const GET_VALIDATOR_TOTAL_STAKE_SUCCESS = 'GET_VALIDATOR_TOTAL_STAKE_SUCCESS';

export const GET_VALIDATOR_DELEGATED_STAKE = 'GET_VALIDATOR_DELEGATED_STAKE';
export const GET_VALIDATOR_DELEGATED_STAKE_SUCCESS = 'GET_VALIDATOR_DELEGATED_STAKE_SUCCESS';

export const GET_VALIDATOR_ACCOUNTABLE_TOTAL_STAKE = 'GET_VALIDATOR_ACCOUNTABLE_TOTAL_STAKE';
export const GET_VALIDATOR_ACCOUNTABLE_TOTAL_STAKE_SUCCESS = 'GET_VALIDATOR_ACCOUNTABLE_TOTAL_STAKE_SUCCESS';

export const GET_VALIDATOR_ACCOUNTABLE_SELF_STAKE = 'GET_VALIDATOR_ACCOUNTABLE_SELF_STAKE';
export const GET_VALIDATOR_ACCOUNTABLE_SELF_STAKE_SUCCESS = 'GET_VALIDATOR_ACCOUNTABLE_SELF_STAKE_SUCCESS';

export const GET_VALIDATORS_WITHDRAWAL_INFO = 'GET_VALIDATORS_WITHDRAWAL_INFO';
export const GET_VALIDATORS_WITHDRAWAL_INFO_SUCCESS = 'GET_VALIDATORS_WITHDRAWAL_INFO_SUCCESS';

// Tables
export const GET_VALIDATORS_MEMBERS = 'GET_VALIDATORS_MEMBERS';
export const SET_VALIDATORS_MEMBERS = 'SET_VALIDATORS_MEMBERS';

// Additional
export const GET_IS_USER_VALIDATOR = 'GET_IS_USER_VALIDATOR';
export const SET_IS_USER_VALIDATOR = 'SET_IS_USER_VALIDATOR';

export const GET_VALIDATORS_MINIMUM_TIME_LOCK = 'GET_VALIDATORS_MINIMUM_TIME_LOCK';
export const SET_VALIDATORS_MINIMUM_TIME_LOCK = 'SET_VALIDATORS_MINIMUM_TIME_LOCK';

export const GET_VALIDATORS_TIME_LOCKS = 'GET_VALIDATORS_TIME_LOCKS';
export const SET_VALIDATORS_TIME_LOCKS = 'SET_VALIDATORS_TIME_LOCKS';

export const GET_COMPOUND_RATE_KEEPER_EXISTS = 'GET_COMPOUND_RATE_KEEPER_EXISTS';
export const SET_COMPOUND_RATE_KEEPER_EXISTS = 'SET_COMPOUND_RATE_KEEPER_EXISTS';

export const SET_INACTIVE_VALIDATORS = 'SET_INACTIVE_VALIDATORS';
