export const SET_VALIDATORS_WITHDRAW = 'SET_VALIDATORS_WITHDRAW'
export const SET_VALIDATORS_ANNOUNCE_WITHDRAWAL = 'SET_VALIDATORS_ANNOUNCE_WITHDRAWAL'
export const SET_VALIDATORS_COMMIT_STAKE = 'SET_VALIDATORS_COMMIT_STAKE'

export const SET_VALIDATORS_SHORT_LIST = 'SET_VALIDATOR_SHORT_LIST'
export const GET_VALIDATORS_SHORT_LIST = 'GET_VALIDATOR_SHORT_LIST'

export const SET_VALIDATORS_WITHDRAWAL_INFO = 'SET_VALIDATORS_WITHDRAWAL_INFO'
export const GET_VALIDATORS_WITHDRAWAL_INFO = 'GET_VALIDATORS_WITHDRAWAL_INFO'

export const GET_VALIDATORS_DELEGATORS_SHARE = 'GET_VALIDATORS_DELEGATORS_SHARE'
export const SET_VALIDATORS_DELEGATORS_SHARE = 'SET_VALIDATORS_DELEGATORS_SHARE'

export const GET_VALIDATORS_INTEREST_RATE = 'GET_VALIDATORS_INTEREST_RATE'
export const SET_VALIDATORS_INTEREST_RATE = 'SET_VALIDATORS_INTEREST_RATE'

export const GET_VALIDATORS_TOTAL_STAKE = 'GET_VALIDATORS_TOTAL_STAKE'
export const SET_VALIDATORS_TOTAL_STAKE = 'SET_VALIDATORS_TOTAL_STAKE'

export const GET_VALIDATORS_OWN_STAKE = 'GET_VALIDATORS_OWN_STAKE'
export const SET_VALIDATORS_OWN_STAKE = 'SET_VALIDATORS_OWN_STAKE'

export const GET_VALIDATORS_DELEGATED_STAKE = 'GET_VALIDATORS_DELEGATED_STAKE'
export const SET_VALIDATORS_DELEGATED_STAKE = 'SET_VALIDATORS_DELEGATED_STAKE'

export const SET_VALIDATORS_ACCOUNTABLE_TOTAL_STAKE = 'SET_VALIDATORS_ACCOUNTABLE_TOTAL_STAKE'
export const GET_VALIDATORS_ACCOUNTABLE_TOTAL_STAKE = 'GET_VALIDATORS_ACCOUNTABLE_TOTAL_STAKE'

export const GET_VALIDATORS_MEMBERS = 'GET_VALIDATORS_MEMBERS'
export const GET_VALIDATORS_MEMBERS_SUCCESS = 'GET_VALIDATORS_MEMBERS_SUCCESS'
export const GET_VALIDATORS_MEMBERS_ERROR = 'GET_VALIDATORS_MEMBERS_ERROR'

export const GET_VALIDATORS_SELF_STAKE = 'GET_VALIDATORS_SELF_STAKE'
export const SET_VALIDATORS_SELF_STAKE = 'SET_VALIDATORS_SELF_STAKE'

export const SET_VALIDATORS_DELEGATORS_SHARE_SEND = 'SET_VALIDATORS_DELEGATORS_SHARE_SEND'
export const SET_VALIDATORS_INTEREST_RATE_SEND = 'SET_VALIDATORS_INTEREST_RATE_SEND'

export const GET_IS_USER_VALIDATOR = 'GET_IS_USER_VALIDATOR'
export const SET_IS_USER_VALIDATOR = 'SET_IS_USER_VALIDATOR'

export const GET_VALIDATORS_MINIMUM_TIME_LOCK = 'GET_VALIDATORS_MINIMUM_TIME_LOCK'
export const GET_VALIDATORS_TIME_LOCKS = 'GET_VALIDATORS_TIME_LOCKS'

export const SET_VALIDATORS_MINIMUM_TIME_LOCK = 'SET_VALIDATORS_MINIMUM_TIME_LOCK'
export const SET_VALIDATORS_TIME_LOCKS = 'SET_VALIDATORS_TIME_LOCKS'

export const SET_VALIDATORS_ENTER_SHORT_LIST = 'SET_ENTER_SHORT_LIST'

export const GET_COMPOUND_RATE_KEEPER_EXISTS = 'GET_COMPOUND_RATE_KEEPER_EXISTS'
export const SET_COMPOUND_RATE_KEEPER_EXISTS = 'SET_COMPOUND_RATE_KEEPER_EXISTS'
