export const GET_VESTING_BALANCE = 'GET_VESTING_BALANCE';
export const GET_VESTING_MINIMUM_TIME_LOCK = 'GET_VESTING_MINIMUM_TIME_LOCK';
export const GET_VESTING_TIME_LOCKS = 'GET_VESTING_TIME_LOCKS';

export const SET_VESTING_BALANCE = 'SET_VESTING_BALANCE';
export const SET_VESTING_MINIMUM_TIME_LOCK = 'SET_VESTING_MINIMUM_TIME_LOCK';
export const SET_VESTING_TIME_LOCKS = 'SET_VESTING_TIME_LOCKS';

export const SET_VESTING_WITHDRAW = 'SET_VESTING_WITHDRAW';
export const SET_VESTING_DEPOSIT = 'SET_VESTING_DEPOSIT';
