export const GET_Q_PROPOSALS_COUNT = 'GET_Q_PROPOSALS_COUNT'
export const SET_Q_PROPOSALS_COUNT = 'SET_Q_PROPOSALS_COUNT'

export const GET_Q_PROPOSALS = 'GET_Q_PROPOSALS'

export const SET_Q_ACTIVE_PROPOSALS = 'SET_Q_ACTIVE_PROPOSALS'
export const SET_Q_ENDED_PROPOSALS = 'SET_Q_ENDED_PROPOSALS'
