
export const GET_Q_PROPOSAL = 'GET_Q_PROPOSAL'
export const GET_Q_PROPOSAL_SUCCESS = 'GET_Q_PROPOSAL_SUCCESS'
export const GET_Q_EMPTY_PROPOSAL_SUCCESS = 'GET_Q_EMPTY_PROPOSAL_SUCCESS'
export const GET_Q_PROPOSAL_ERROR = 'GET_Q_PROPOSAL_ERROR'

export const GET_Q_ONE_PROPOSAL_SUCCESS = 'GET_Q_ONE_PROPOSAL_SUCCESS'

export const GET_Q_PROPOSAL_ENDED = 'GET_Q_PROPOSAL_ENDED'
export const GET_Q_PROPOSAL_ENDED_SUCCESS = 'GET_Q_PROPOSAL_ENDED_SUCCESS'
export const GET_Q_EMPTY_PROPOSAL_ENDED_SUCCESS = 'GET_Q_EMPTY_PROPOSAL_ENDED_SUCCESS'
export const GET_Q_PROPOSAL_ENDED_ERROR = 'GET_Q_PROPOSAL_ENDED_ERROR'

// proposals
export const GET_Q_PROPOSALS_COUNT = 'GET_Q_PROPOSALS_COUNT'
export const SET_Q_PROPOSALS_COUNT = 'SET_Q_PROPOSALS_COUNT'

export const GET_Q_PROPOSALS = 'GET_Q_PROPOSALS'

export const SET_Q_ACTIVE_PROPOSALS = 'SET_Q_ACTIVE_PROPOSALS'
export const SET_Q_ACTIVE_PROPOSALS_ERROR = 'SET_Q_ACTIVE_PROPOSALS_ERROR'
export const SET_Q_ACTIVE_PROPOSALS_LOADING = 'SET_Q_ACTIVE_PROPOSALS_LOADING'

export const SET_Q_ENDED_PROPOSALS = 'SET_Q_ENDED_PROPOSALS'
export const SET_Q_ENDED_PROPOSALS_LOADING = 'SET_Q_ENDED_PROPOSALS_LOADING'
export const SET_Q_ENDED_PROPOSALS_ERROR = 'SET_Q_ENDED_PROPOSALS_ERROR'
