
export const GET_Q_PROPOSAL = 'GET_Q_PROPOSAL'
export const GET_Q_PROPOSAL_SUCCESS = 'GET_Q_PROPOSAL_SUCCESS'
export const GET_Q_EMPTY_PROPOSAL_SUCCESS = 'GET_Q_EMPTY_PROPOSAL_SUCCESS'
export const GET_Q_PROPOSAL_ERROR = 'GET_Q_PROPOSAL_ERROR'

export const GET_Q_ONE_PROPOSAL_SUCCESS = 'GET_Q_ONE_PROPOSAL_SUCCESS'

export const GET_Q_PROPOSAL_ENDED = 'GET_Q_PROPOSAL_ENDED'
export const GET_Q_PROPOSAL_ENDED_SUCCESS = 'GET_Q_PROPOSAL_ENDED_SUCCESS'
export const GET_Q_EMPTY_PROPOSAL_ENDED_SUCCESS = 'GET_Q_EMPTY_PROPOSAL_ENDED_SUCCESS'
export const GET_Q_PROPOSAL_ENDED_ERROR = 'GET_Q_PROPOSAL_ENDED_ERROR'

export const GET_Q_PROPOSALS_COUNT = 'GET_Q_PROPOSALS_COUNT'
export const SET_Q_PROPOSALS_COUNT = 'SET_Q_PROPOSALS_COUNT'

// proposals
export const GET_Q_PROPOSALS_LIST = 'GET_Q_PROPOSALS_LIST'

export const SET_Q_ENDED_PROPOSALS = 'SET_Q_ENDED_PROPOSALS'
export const SET_Q_ENDED_PROPOSALS_ERROR = 'SET_Q_ENDED_PROPOSALS_ERROR'

export const SET_Q_PROPOSALS_LIST = 'SET_Q_PROPOSALS_LIST'
export const SET_Q_PROPOSALS_LIST_ERROR = 'SET_Q_PROPOSALS_LIST_ERROR'
