export const CREATE_PROPOSAL = 'CREATE_PROPOSAL';
export const EXECUTE_PROPOSAL = 'EXECUTE_PROPOSAL';

export const SET_VOTE_DETAILS = 'SET_VOTE_DETAILS';
export const VOTE_FOR_PROPOSAL = 'VOTE_FOR_PROPOSAL';

export const GET_NUMBER_ALL_PROPOSALS = 'GET_NUMBER_ALL_ENDED_PROPOSALS';
export const GET_CONSTITUTION_HASH = 'GET_CONSTITUTION_HASH';
export const GET_CONSTITUTION_HASH_SUCCESS = 'GET_CONSTITUTION_HASH_SUCCESS';

export const GET_BASE_VOTING_WEIGHT_INFO = 'GET_BASE_VOTING_WEIGHT_INFO';
export const SET_BASE_VOTING_WEIGHT_INFO = 'SET_BASE_VOTING_WEIGHT_INFO';

export const GET_PROPOSALS_BY_TYPE = 'GET_PROPOSALS_BY_TYPE';

export const SET_NEW_PARAMETER = 'SET_NEW_PARAMETER';
