export const CREATE_AUCTION = 'CREATE_AUCTION'
export const CREATE_AUCTION_SUCCESS = 'CREATE_AUCTION_SUCCESS'
export const CREATE_AUCTION_ERROR = 'CREATE_AUCTION_ERROR'

export const GET_AUCTIONS_LIST = 'GET_AUCTIONS_LIST'
export const GET_AUCTIONS_LIST_SUCCESS = 'GET_AUCTIONS_LIST_SUCCESS'
export const GET_AUCTIONS_LIST_ERROR = 'GET_AUCTIONS_LIST_ERROR'

export const GET_ENDED_AUCTIONS_LIST = 'GET_ENDED_AUCTIONS_LIST'
export const GET_ENDED_AUCTIONS_LIST_SUCCESS = 'GET_ENDED_AUCTIONS_LIST_SUCCESS'
export const GET_ENDED_AUCTIONS_LIST_ERROR = 'GET_ENDED_AUCTIONS_LIST_ERROR'

export const BID_FOR_AUCTION = 'BID_FOR_AUCTION'
export const BID_FOR_AUCTION_SUCCESS = 'BID_FOR_AUCTION_SUCCESS'
export const BID_FOR_AUCTION_ERROR = 'BID_FOR_AUCTION_ERROR'

export const EXECUTE_AUCTION = 'EXECUTE_AUCTION'
export const EXECUTE_AUCTION_SUCCESS = 'EXECUTE_AUCTION_SUCCESS'
export const EXECUTE_AUCTION_ERROR = 'EXECUTE_AUCTION_ERROR'

export const GET_AUCTION = 'GET_AUCTION'
export const GET_AUCTION_SUCCESS = 'GET_AUCTION_SUCCESS'
export const GET_EMPTY_AUCTION_SUCCESS = 'GET_EMPTY_AUCTION_SUCCESS'
export const GET_AUCTION_ERROR = 'GET_AUCTION_ERROR'

export const SET_APPROVE_MODAL_BTN = 'SET_APPROVE_MODAL_BTN'

// fetch auct
export const GET_AUCTIONS = 'GET_AUCTIONS'

export const SET_LIQUIDATION_AUCTIONS = 'SET_LIQUIDATION_AUCTIONS'
export const SET_SYSTEM_DEBT_AUCTIONS = 'SET_SYSTEM_DEBT_AUCTIONS'
export const SET_SYSTEM_SURPLUS_AUCTIONS = 'SET_SYSTEM_SURPLUS_AUCTIONS'

export const SET_LIQUIDATION_AUCTIONS_COUNT = 'SET_LIQUIDATION_AUCTIONS_COUNT'
export const SET_SYSTEM_DEBT_AUCTIONS_COUNT = 'SET_SYSTEM_DEBT_AUCTIONS_COUNT'
export const SET_SYSTEM_SURPLUS_AUCTIONS_COUNT = 'SET_SYSTEM_SURPLUS_AUCTIONS_COUNT'

export const GET_ONE_AUCTION = 'GET_ONE_AUCTION'
export const SET_ONE_AUCTION = 'SET_ONE_AUCTION'
