export const CREATE_AUCTION = 'CREATE_AUCTION'
export const BID_FOR_AUCTION = 'BID_FOR_AUCTION'
export const EXECUTE_AUCTION = 'EXECUTE_AUCTION'

export const SET_APPROVE_MODAL_BTN = 'SET_APPROVE_MODAL_BTN'

export const GET_AUCTIONS = 'GET_AUCTIONS'

export const SET_LIQUIDATION_AUCTIONS = 'SET_LIQUIDATION_AUCTIONS'
export const SET_SYSTEM_DEBT_AUCTIONS = 'SET_SYSTEM_DEBT_AUCTIONS'
export const SET_SYSTEM_SURPLUS_AUCTIONS = 'SET_SYSTEM_SURPLUS_AUCTIONS'

export const GET_ONE_AUCTION = 'GET_ONE_AUCTION'
export const SET_ONE_AUCTION = 'SET_ONE_AUCTION'
