export const SET_LOCK_DATA_IS_LOADING = 'SET_VAL_DATA_IS_LOADING'
export const SET_LOCK_DATA_IS_LOADED = 'SET_VAL_DATA_IS_LOADED'
export const SET_LOCK_ERROR = 'SET_VAL_ERROR'

export const GET_QVAULT_AMOUNT = 'GET_QVAULT_AMOUNT'
export const GET_ROOTNODE_AMOUNT = 'GET_ROOTNODE_AMOUNT'
export const GET_VALIDATOR_AMOUNT = 'GET_VALIDATOR_AMOUNT'

export const SET_QVAULT_AMOUNT = 'SET_QVAULT_AMOUNT'
export const SET_ROOTNODE_AMOUNT = 'SET_ROOTNODE_AMOUNT'
export const SET_VALIDATOR_AMOUNT = 'SET_VALIDATOR_AMOUNT'

export const SET_LOCKEDAMOUNT_CALL = 'SET_LOCKEDAMOUNT_CALL'

export const SET_PURGEAMOUNT_CALL = 'SET_PURGEAMOUNT_CALL'
