export const IS_USER_EPDR_MEMBER = 'IS_USER_EPDR_MEMBER';
export const IS_USER_EPDR_MEMBER_SUCCESS = 'IS_USER_EPDR_MEMBER_SUCCESS';

export const IS_USER_EPQFI_MEMBER = 'IS_USER_EPQFI_MEMBER';
export const IS_USER_EPQFI_MEMBER_SUCCESS = 'IS_USER_EPQFI_MEMBER_SUCCESS';

export const GET_EPDR_MEMBERS = 'GET_EPDR_MEMBERS';
export const GET_EPDR_MEMBERS_SUCCESS = 'GET_EPDR_MEMBERS_SUCCESS';
export const GET_EPDR_MEMBERS_ERROR = 'GET_EPDR_MEMBERS_ERROR';

export const GET_EPQFI_MEMBERS = 'GET_EPQFI_MEMBERS';
export const GET_EPQFI_MEMBERS_SUCCESS = 'GET_EPQFI_MEMBERS_SUCCESS';
export const GET_EPQFI_MEMBERS_ERROR = 'GET_EPQFI_MEMBERS_ERROR';
