export const SET_QV_DATA_IS_LOADING = 'SET_QV_DATA_IS_LOADING';

export const GET_QV_USER_BALANCE = 'GET_QV_USER_BALANCE';
export const SET_QV_USER_BALANCE = 'SET_QV_USER_BALANCE';

export const GET_QV_LOCKED_ASSETS = 'GET_QV_LOCKED_ASSETS';
export const SET_QV_LOCKED_ASSETS = 'SET_QV_LOCKED_ASSETS';

export const SET_QV_ERROR = 'SET_QV_ERROR';

// Action without write to Store
export const SET_QV_DEPOSIT_CALL = 'SET_QV_DEPOSIT_CALL';
export const SET_QV_WITHDRAW_CALL = 'SET_QV_WITHDRAW_CALL';
export const SET_QV_LOCK_AMOUNT = 'SET_QV_LOCK_AMOUNT';
export const SET_QV_UNLOCK_AMOUNT = 'SET_QV_UNLOCK_AMOUNT';

export const GET_DELEGATIONS_LIST = 'GET_DELEGATIONS_LIST';
export const GET_DELEGATIONS_LIST_SUCCESS = 'GET_DELEGATIONS_LIST_SUCCESS';
export const GET_DELEGATIONS_LIST_ERROR = 'GET_DELEGATIONS_LIST_ERROR';

export const GET_QV_BALANCE = 'GET_QV_BALANCE';
export const GET_QV_BALANCE_SUCCESS = 'GET_QV_BALANCE_SUCCESS';

export const ON_CLAIM_STAKE_DELEGATOR_REWARD = 'ON_CLAIM_STAKE_DELEGATOR_REWARD';

export const GET_OUTSTANDING_DELEGATION_REWARDS = 'GET_OUTSTANDING_DELEGATION_REWARDS';
export const GET_OUTSTANDING_DELEGATION_REWARDS_SUCCESS = 'GET_OUTSTANDING_DELEGATION_REWARDS_SUCCESS';
export const GET_OUTSTANDING_DELEGATION_REWARDS_ERROR = 'GET_OUTSTANDING_DELEGATION_REWARDS_ERROR';
