export const GET_AVAILABLE_AMOUNT = 'GET_AVAILABLE_AMOUNT'
export const GET_AVAILABLE_AMOUNT_SUCCESS = 'GET_AVAILABLE_AMOUNT_SUCCESS'
export const GET_AVAILABLE_AMOUNT_ERROR = 'GET_AVAILABLE_AMOUNT_ERROR'
