export const SET_VAL_DATA_IS_LOADING = 'SET_VAL_DATA_IS_LOADING'
export const SET_VAL_DATA_IS_LOADED = 'SET_VAL_DATA_IS_LOADED'
export const SET_VAL_ERROR = 'SET_VAL_ERROR'

export const GET_VAL_DELEGATORS_SHARE = 'GET_VAL_DELEGATORS_SHARE'
export const SET_VAL_DELEGATORS_SHARE = 'SET_VAL_DELEGATORS_SHARE'

export const GET_VAL_INTEREST_RATE = 'GET_VAL_INTEREST_RATE'
export const SET_VAL_INTEREST_RATE = 'SET_VAL_INTEREST_RATE'

export const GET_VAL_TOTAL_STAKE = 'GET_VAL_TOTAL_STAKE'
export const SET_VAL_TOTAL_STAKE = 'SET_VAL_TOTAL_STAKE'

export const GET_VAL_OWN_STAKE = 'GET_VAL_OWN_STAKE'
export const SET_VAL_OWN_STAKE = 'SET_VAL_OWN_STAKE'

export const GET_VAL_DELEGATED_STAKE = 'GET_VAL_DELEGATED_STAKE'
export const SET_VAL_DELEGATED_STAKE = 'SET_VAL_DELEGATED_STAKE'

export const GET_VAL_ACC_TOTAL_STAKE = 'GET_VAL_ACC_TOTAL_STAKE'
export const SET_VAL_ACC_TOTAL_STAKE = 'SET_VAL_ACC_TOTAL_STAKE'

export const GET_VALIDATORS_MEMBERS = 'GET_VALIDATORS_MEMBERS'
export const GET_VALIDATORS_MEMBERS_SUCCESS = 'GET_VALIDATORS_MEMBERS_SUCCESS'
export const GET_VALIDATORS_MEMBERS_ERROR = 'GET_VALIDATORS_MEMBERS_ERROR'

export const GET_VAL_SELF_STAKE = 'GET_VAL_SELF_STAKE'
export const SET_VAL_SELF_STAKE = 'SET_VAL_SELF_STAKE'

// Action without write to Store
export const SET_VAL_DELEGATORS_SHARE_SEND = 'SET_VAL_DELEGATORS_SHARE_SEND'
export const SET_VAL_INTEREST_RATE_SEND = 'SET_VAL_INTEREST_RATE_SEND'

export const IS_USER_VALIDATOR = 'IS_USER_VALIDATOR'
export const IS_USER_VALIDATOR_SUCCESS = 'IS_USER_VALIDATOR_SUCCESS'

// sdk action-types
export const GET_VALIDATORS_MINIMUM_TIME_LOCK = 'GET_VALIDATORS_MINIMUM_TIME_LOCK'
export const GET_VALIDATORS_TIME_LOCKS = 'GET_VALIDATORS_TIME_LOCKS'

export const SET_VALIDATORS_MINIMUM_TIME_LOCK = 'SET_VALIDATORS_MINIMUM_TIME_LOCK'
export const SET_VALIDATORS_TIME_LOCKS = 'SET_VALIDATORS_TIME_LOCKS'
