export const GET_AVAILABLE_AMOUNT = 'GET_AVAILABLE_AMOUNT'
export const GET_AVAILABLE_AMOUNT_SUCCESS = 'GET_AVAILABLE_AMOUNT_SUCCESS'
export const GET_AVAILABLE_AMOUNT_ERROR = 'GET_AVAILABLE_AMOUNT_ERROR'

export const SET_SYSTEM_RESERVE_BALANCE = 'SET_SYSTEM_RESERVE_BALANCE'
export const GET_SYSTEM_RESERVE_BALANCE = 'GET_SYSTEM_RESERVE_BALANCE'
