export const GET_VRP_BALANCE = 'GET_VRP_BALANCE';
export const GET_VRP_BALANCE_SUCCESS = 'GET_VRP_BALANCE_SUCCESS';

export const GET_VRP_POOL_INFO = 'GET_VRP_POOL_INFO';
export const GET_VRP_POOL_INFO_SUCCESS = 'GET_VRP_POOL_INFO_SUCCESS';

export const GET_VRP_DELEGATORS_SHARE = 'GET_VRP_DELEGATORS_SHARE';
export const GET_VRP_DELEGATORS_SHARE_SUCCESS = 'GET_VRP_DELEGATORS_SHARE_SUCCESS';

export const GET_VRP_LAST_UPDATE_OF_COMPOUND_RATE = 'GET_VRP_LAST_UPDATE_OF_COMPOUND_RATE';
export const GET_VRP_LAST_UPDATE_OF_COMPOUND_RATE_SUCCESS = 'GET_VRP_LAST_UPDATE_OF_COMPOUND_RATE_SUCCESS';
