export const GET_VRP_BALANCE = 'GET_VRP_BALANCE'
export const SET_VRP_BALANCE = 'SET_VRP_BALANCE'

export const GET_VRP_POOL_INFO = 'GET_VRP_POOL_INFO'
export const SET_VRP_POOL_INFO = 'SET_VRP_POOL_INFO'

export const SET_VRP_DELEGATOR_SHARE = 'SET_VRP_DELEGATOR_SHARE'
export const SET_VRP_DELEGATOR_SHARE_DATA = 'SET_VRP_DELEGATOR_SHARE_DATA'
export const GET_VRP_DELEGATOR_SHARE = 'GET_VRP_DELEGATOR_SHARE'

export const SET_VRP_UPDATE_VALIDATORS_COMPOUND_RATE = 'SET_VRP_UPDATE_VALIDATORS_COMPOUND_RATE'
export const SET_VRP_LAST_UPDATE_OF_COMPOUND_RATE_DATA = 'SET_VRP_LAST_UPDATE_OF_COMPOUND_RATE_DATA'
export const GET_VRP_LAST_UPDATE_OF_COMPOUND_RATE = 'GET_VRP_LAST_UPDATE_OF_COMPOUND_RATE'

export const SET_VRP_LOADING_COMPOUND_RATE = 'SET_VRP_LOADING_COMPOUND_RATE'
export const SET_IS_STAKER_REWARD_POOL_MSG_DISPLAYED = 'SET_IS_STAKER_REWARD_POOL_MSG_DISPLAYED'
