export const GET_ROOT_NODE_PROPOSAL = 'GET_ROOT_NODE_PROPOSAL'
export const GET_ROOT_NODE_PROPOSAL_SUCCESS = 'GET_ROOT_NODE_PROPOSAL_SUCCESS'
export const GET_ROOT_NODE_EMPTY_PROPOSAL_SUCCESS = 'GET_ROOT_NODE_EMPTY_PROPOSAL_SUCCESS'
export const GET_ROOT_NODE_PROPOSAL_ERROR = 'GET_ROOT_NODE_PROPOSAL_ERROR'

export const GET_ONE_ROOT_NODE_PROPOSAL_SUCCESS = 'GET_ONE_ROOT_NODE_PROPOSAL_SUCCESS'

export const GET_ROOT_NODE_ENDED_PROPOSAL = 'GET_ROOT_NODE_ENDED__PROPOSAL'
export const GET_ROOT_NODE_PROPOSAL_ENDED_SUCCESS = 'GET_ROOT_NODE_PROPOSAL_ENDED_SUCCESS'
export const GET_ROOT_NODE_EMPTY_PROPOSAL_ENDED_SUCCESS = 'GET_ROOT_NODE_EMPTY_PROPOSAL_ENDED_SUCCESS'
export const GET_ROOT_NODE_PROPOSAL_ENDED_ERROR = 'GET_ROOT_NODE_PROPOSAL_ENDED_ERROR'
/// /////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
export const GET_ROOT_PROPOSALS_COUNT = 'GET_ROOT_PROPOSALS_COUNT'
export const SET_ROOT_PROPOSALS_COUNT = 'SET_ROOT_PROPOSALS_COUNT'

export const GET_ROOT_PROPOSALS = 'GET_ROOT_PROPOSALS'

export const SET_ROOT_ACTIVE_PROPOSALS = 'SET_ROOT_ACTIVE_PROPOSALS'
export const SET_ROOT_ACTIVE_PROPOSALS_ERROR = 'SET_ROOT_ACTIVE_PROPOSALS_ERROR'
export const SET_ROOT_ACTIVE_PROPOSALS_LOADING = 'SET_ROOT_ACTIVE_PROPOSALS_LOADING'

export const SET_ROOT_ENDED_PROPOSALS = 'SET_ROOT_ENDED_PROPOSALS'
export const SET_ROOT_ENDED_PROPOSALS_LOADING = 'SET_ROOT_ENDED_PROPOSALS_LOADING'
export const SET_ROOT_ENDED_PROPOSALS_ERROR = 'SET_Q_ENDED_PROPOSALS_ERROR'
