export const GET_ROOT_PROPOSALS_COUNT = 'GET_ROOT_PROPOSALS_COUNT'
export const SET_ROOT_PROPOSALS_COUNT = 'SET_ROOT_PROPOSALS_COUNT'

export const GET_ROOT_PROPOSALS = 'GET_ROOT_PROPOSALS'

export const SET_ROOT_ACTIVE_PROPOSALS = 'SET_ROOT_ACTIVE_PROPOSALS'
export const SET_ROOT_ENDED_PROPOSALS = 'SET_ROOT_ENDED_PROPOSALS'
