export const SET_PERFORM_NETTING = 'SET_PERFORM_NETTING';

export const GET_SC_TOTAL_SUPPLY = 'GET_SC_TOTAL_SUPPLY';
export const GET_SC_TOTAL_SUPPLY_SUCCESS = 'GET_SC_TOTAL_SUPPLY_SUCCESS';
export const GET_SC_TOTAL_SUPPLY_ERROR = 'GET_SC_TOTAL_SUPPLY_ERROR';

export const GET_SB_BALANCE = 'GET_SB_BALANCE';
export const GET_SB_BALANCE_SUCCESS = 'GET_SB_BALANCE_SUCCESS';
export const GET_SB_BALANCE_ERROR = 'GET_SB_BALANCE_ERROR';

export const GET_SB_DEBT = 'GET_SB_DEBT';
export const GET_SB_DEBT_SUCCESS = 'GET_SB_DEBT_SUCCESS';
export const GET_SB_DEBT_ERROR = 'GET_SB_DEBT_ERROR';

export const GET_SB_SURPLUS = 'GET_SB_SURPLUS';
export const GET_SB_SURPLUS_SUCCESS = 'GET_SB_SURPLUS_SUCCESS';
export const GET_SB_SURPLUS_ERROR = 'GET_SB_SURPLUS_ERROR';

export const GET_SR_AVAILABLE_AMOUNT = 'GET_SR_AVAILABLE_AMOUNT';
export const GET_SR_AVAILABLE_AMOUNT_SUCCESS = 'GET_SR_AVAILABLE_AMOUNT_SUCCESS';
export const GET_SR_AVAILABLE_AMOUNT_ERROR = 'GET_SR_AVAILABLE_AMOUNT_ERROR';

export const GET_SR_BALANCE = 'GET_SR_BALANCE';
export const GET_SR_BALANCE_SUCCESS = 'GET_SR_BALANCE_SUCCESS';
export const GET_SR_BALANCE_ERROR = 'GET_SR_BALANCE_ERROR';
