export const GET_SAVING_BALANCE_DETAILS = 'GET_SAVING_BALANCE_DETAILS'
export const SET_SAVING_BALANCE_DETAILS = 'SET_SAVING_BALANCE_DETAILS'

export const GET_SAVING_AVIABLE_TO_DEPOSIT = 'GET_SAVING_AVIABLE_TO_DEPOSIT'
export const SET_SAVING_AVIABLE_TO_DEPOSIT = 'SET_SAVING_AVIABLE_TO_DEPOSIT'

export const GET_SAVING_ALLOWANCE = 'GET_SAVING_ALLOWANCE'
export const SET_SAVING_ALLOWANCE = 'SET_SAVING_ALLOWANCE'

export const SET_SAVING_DEPOSIT = 'SET_SAVING_DEPOSIT'
export const SET_SAVING_WITHDRAW = 'SET_SAVING_WITHDRAW'
export const SET_SAVING_APROVE = 'SET_SAVING_APROVE'
