export const IS_USER_EPDR_MEMBER = 'IS_USER_EPDR_MEMBER';
export const IS_USER_EPDR_MEMBER_SUCCESS = 'IS_USER_EPDR_MEMBER_SUCCESS';

export const IS_USER_EPQFI_MEMBER = 'IS_USER_EPQFI_MEMBER';
export const IS_USER_EPQFI_MEMBER_SUCCESS = 'IS_USER_EPQFI_MEMBER_SUCCESS';
