export const GET_ADDRESS_PARAMETER = 'GET_ADDRESS_PARAMETER';
export const GET_ADDRESS_PARAMETER_SUCCESS = 'GET_ADDRESS_PARAMETER_SUCCESS';

export const GET_BOOLEAN_PARAMETER = 'GET_BOOLEAN_PARAMETER';
export const GET_BOOLEAN_PARAMETER_SUCCESS = 'GET_BOOLEAN_PARAMETER_SUCCESS';

export const GET_STRING_PARAMETER = 'GET_STRING_PARAMETER';
export const GET_STRING_PARAMETER_SUCCESS = 'GET_STRING_PARAMETER_SUCCESS';

export const GET_BYTES_PARAMETER = 'GET_BYTES_PARAMETER';
export const GET_BYTES_PARAMETER_SUCCESS = 'GET_BYTES_PARAMETER_SUCCESS';

export const GET_UINT_PARAMETER = 'GET_UINT_PARAMETER';
export const GET_UINT_PARAMETER_SUCCESS = 'GET_UINT_PARAMETER_SUCCESS';


export const GET_PARAMETER_VALUE_BY_KEY = 'GET_PARAMETER_VALUE_BY_KEY';
export const GET_PARAMETER_VALUE_BY_KEY_SUCCESS = 'GET_PARAMETER_VALUE_BY_KEY_SUCCESS';
export const GET_PARAMETER_VALUE_BY_KEY_ERROR = 'GET_PARAMETER_VALUE_BY_KEY_ERROR';
