export const GET_SURPLUS = 'GET_SURPLUS';
export const GET_SURPLUS_SUCCESS = 'GET_SURPLUS_SUCCESS';
export const GET_SURPLUS_ERROR = 'GET_SURPLUS_ERROR';

export const GET_DEBT = 'GET_DEBT';
export const GET_DEBT_SUCCESS = 'GET_DEBT_SUCCESS';
export const GET_DEBT_ERROR = 'GET_DEBT_ERROR';

export const GET_SYSTEM_BALANCE = 'GET_SYSTEM_BALANCE';
export const GET_SYSTEM_BALANCE_SUCCESS = 'GET_SYSTEM_BALANCE_SUCCESS';
export const GET_SYSTEM_BALANCE_ERROR = 'GET_SYSTEM_BALANCE_ERROR';

export const ON_PERFORM_NETTING = 'ON_PERFORM_NETTING';
export const ON_PERFORM_NETTING_SUCCESS = 'ON_PERFORM_NETTING_SUCCESS';
export const ON_PERFORM_NETTING_ERROR = 'ON_PERFORM_NETTING_ERROR';
