export const DETECT_ETHEREUM_PROVIDER = "DETECT_ETHEREUM_PROVIDER";
export const DETECT_ETHEREUM_PROVIDER_SUCCESS = "DETECT_ETHEREUM_PROVIDER_SUCCESS";
export const DETECT_ETHEREUM_PROVIDER_ERROR = "DETECT_ETHEREUM_PROVIDER_ERROR";
