export const SET_VAL_DATA_IS_LOADING = 'SET_VAL_DATA_IS_LOADING';
export const SET_VAL_DATA_IS_LOADED = 'SET_VAL_DATA_IS_LOADED';
export const SET_VAL_ERROR = 'SET_VAL_ERROR';

export const GET_VAL_DELEGATORS_SHARE = 'GET_VAL_DELEGATORS_SHARE';
export const SET_VAL_DELEGATORS_SHARE = 'SET_VAL_DELEGATORS_SHARE';

export const GET_VAL_INTEREST_RATE = 'GET_VAL_INTEREST_RATE';
export const SET_VAL_INTEREST_RATE = 'SET_VAL_INTEREST_RATE';

export const GET_VAL_TOTAL_STAKE = 'GET_VAL_TOTAL_STAKE';
export const SET_VAL_TOTAL_STAKE = 'SET_VAL_TOTAL_STAKE';

export const GET_VAL_OWN_STAKE = 'GET_VAL_OWN_STAKE';
export const SET_VAL_OWN_STAKE = 'SET_VAL_OWN_STAKE';

export const GET_VAL_DELEGATED_STAKE = 'GET_VAL_DELEGATED_STAKE';
export const SET_VAL_DELEGATED_STAKE = 'SET_VAL_DELEGATED_STAKE';

export const GET_VAL_ACC_TOTAL_STAKE = 'GET_VAL_ACC_TOTAL_STAKE';
export const SET_VAL_ACC_TOTAL_STAKE = 'SET_VAL_ACC_TOTAL_STAKE';

// Action without write to Store
export const SET_VAL_DELEGATORS_SHARE_SEND = 'SET_VAL_DELEGATORS_SHARE_SEND';
export const SET_VAL_INTEREST_RATE_SEND = 'SET_VAL_INTEREST_RATE_SEND';
