export const GET_EXPERT_PROPOSAL = 'GET_EXPERT_PROPOSAL'
export const GET_EXPERT_PROPOSAL_SUCCESS = 'GET_EXPERT_PROPOSAL_SUCCESS'
export const GET_EXPERT_EMPTY_PROPOSAL_SUCCESS = 'GET_EXPERT_EMPTY_PROPOSAL_SUCCESS'
export const GET_EXPERT_PROPOSAL_ERROR = 'GET_EXPERT_PROPOSAL_ERROR'

export const GET_ONE_EXPERT_PROPOSAL_SUCCESS = 'GET_ONE_EXPERT_PROPOSAL_SUCCESS'

export const GET_EXPERT_PROPOSAL_ENDED = 'GET_EXPERT_PROPOSAL_ENDED'
export const GET_EXPERT_PROPOSAL_ENDED_SUCCESS = 'GET_EXPERT_PROPOSAL_ENDED_SUCCESS'
export const GET_EXPERT_EMPTY_PROPOSAL_ENDED_SUCCESS = 'GET_EXPERT_EMPTY_PROPOSAL_ENDED_SUCCESS'
export const GET_EXPERT_PROPOSAL_ENDED_ERROR = 'GET_EXPERT_PROPOSAL_ENDED_ERROR'

/// ///////////////////////////////////////////////////////////////////////////////
export const GET_EXPERT_PROPOSALS_COUNT = 'GET_EXPERT_PROPOSALS_COUNT'
export const SET_EXPERT_PROPOSALS_COUNT = 'SET_EXPERT_PROPOSALS_COUNT'

export const GET_EXPERT_PROPOSALS = 'GET_EXPERT_PROPOSALS'

export const SET_EXPERT_ACTIVE_PROPOSALS = 'SET_EXPERT_ACTIVE_PROPOSALS'
export const SET_EXPERT_ACTIVE_PROPOSALS_ERROR = 'SET_EXPERT_ACTIVE_PROPOSALS_ERROR'
export const SET_EXPERT_ACTIVE_PROPOSALS_LOADING = 'SET_EXPERT_ACTIVE_PROPOSALS_LOADING'

export const SET_EXPERT_ENDED_PROPOSALS = 'SET_EXPERT_ENDED_PROPOSALS'
export const SET_EXPERT_ENDED_PROPOSALS_LOADING = 'SET_EXPERT_ENDED_PROPOSALS_LOADING'
export const SET_EXPERT_ENDED_PROPOSALS_ERROR = 'SET_EXPERT_ENDED_PROPOSALS_ERROR'
