export const GET_EXPERT_PROPOSALS_COUNT = 'GET_EXPERT_PROPOSALS_COUNT'
export const SET_EXPERT_PROPOSALS_COUNT = 'SET_EXPERT_PROPOSALS_COUNT'

export const GET_EXPERT_PROPOSALS = 'GET_EXPERT_PROPOSALS'

export const SET_EXPERT_ACTIVE_PROPOSALS = 'SET_EXPERT_ACTIVE_PROPOSALS'
export const SET_EXPERT_ENDED_PROPOSALS = 'SET_EXPERT_ENDED_PROPOSALS'
