export const SET_CREATE_QBTC_VAULT = 'SET_CREATE_QBTC_VAULT'
export const SET_ADD_COINS_TO_METAMASK = 'SET_ADD_COINS_TO_METAMASK'
export const SET_SHOULD_ADD_COINS = 'SET_SHOULD_ADD_COINS'

export const GET_OUTSTANDING_DEBT = 'GET_OUTSTANDING_DEBT'
export const SET_OUTSTANDING_DEBT = 'SET_OUTSTANDING_DEBT'

export const GET_TOTAL_SAVING_BALANCE = 'GET_TOTAL_SAVING_BALANCE'
export const SET_TOTAL_SAVING_BALANCE = 'SET_TOTAL_SAVING_BALANCE'

export const GET_TOTAL_COLLATERAL_LOCKED = 'GET_TOTAL_COLLATERAL_LOCKED'
export const SET_TOTAL_COLLATERAL_LOCKED = 'SET_TOTAL_COLLATERAL_LOCKED'

export const GET_SAVING_ASSETS = 'GET_SAVING_ASSETS'
export const SET_SAVING_ASSETS = 'SET_SAVING_ASSETS'

export const GET_BORROWING_VAULTS = 'GET_BORROWING_VAULTS'
export const SET_BORROWING_VAULTS = 'SET_BORROWING_VAULTS'

export const GET_TOTAL_SUPPLY = 'GET_TOTAL_SUPPLY'
export const SET_TOTAL_SUPPLY = 'SET_TOTAL_SUPPLY'

export const GET_SAVING_AND_INTEREST_RATE = 'GET_SAVING_AND_INTEREST_RATE'
export const SET_SAVING_RATE = 'GET_SAVING_RATE'
export const SET_INTEREST_RATE = 'GET_INTEREST_RATE'
