export const ESCROW_CAST_OBJECTION = 'ESCROW_CAST_OBJECTION'
export const ESCROW_PROPOSER_REMARK = 'ESCROW_PROPOSER_REMARK'

export const ESCROW_PROPOSE_DECISION = 'ESCROW_PROPOSE_DECISION'
export const ESCROW_RECALL_PROPOSE_DECISION = 'RECALL_PROPOSE_DECISION'
export const ESCROW_CONFIRM_DECISION = 'ESCROW_CONFIRM_DECISION'

export const GET_SLASHING_PROPOSALS_COUNT = 'GET_SLASHING_PROPOSALS_COUNT'
export const SET_SLASHING_PROPOSALS_COUNT = 'SET_SLASHING_PROPOSALS_COUNT'

export const GET_SLASHING_PROPOSALS = 'GET_SLASHING_PROPOSALS'

export const SET_SLASHING_ACTIVE_PROPOSALS = 'SET_SLASHING_ACTIVE_PROPOSALS'
export const SET_SLASHING_ENDED_PROPOSALS = 'SET_SLASHING_ENDED_PROPOSALS'
