export const GET_BORROW_VAULT_INFO = 'GET_BORROW_VAULT_INFO'
export const SET_BORROW_VAULT_INFO = 'SET_BORROW_VAULT_INFO'

export const GET_BORROW_COLLATERAL_INFO = 'GET_BORROW_COLLATERAL_INFO'
export const SET_BORROW_COLLATERAL_INFO = 'SET_BORROW_COLLATERAL_INFO'

export const GET_BORROW_ALLOWANCE = 'GET_BORROW_ALLOWANCE_REPAY'
export const SET_BORROW_ALLOWANCE_REPAY = 'SET_BORROW_ALLOWANCE_REPAY'
export const SET_BORROW_ALLOWANCE_DEPOSIT = 'SET_BORROW_ALLOWANCE_DEPOSIT'

export const SET_BORROW_APPROVE = 'SET_BORROW_APPROVE'

export const SET_BORROW_WITHDRAW = 'SET_BORROW_WITHDRAW'
export const SET_BORROW_REPAY = 'SET_BORROW_REPAY'
export const SET_BORROW_AS_BORROW = 'SET_BORROW_AS_BORROW'
export const SET_BORROW_DEPOSIT = 'SET_BORROW_DEPOSIT'
